version: "3"


services:
  blog:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
    - "${EXPOSED_PORT}:1337"
    networks:
      - mehran-networks

  postgres-blog:
    image: postgres
    container_name: postgres-blog
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - mehran-networks
    volumes: 
      - postgres_volume:/var/lib/postgresql

networks: 
  mehran-networks:
    driver: bridge

volumes:
  postgres_volume:
